version: '3'
services:
  productservice:
    image: swapping-productservice:latest
    network_mode: bridge
    container_name: swapping-productservice
    expose:
      - 8001
    ports:
      - 8001:8001
    restart: unless-stopped
    command: mvn spring-boot:run
