server:
  port: 8001
spring:
  application:
    name: Product Service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-18-233-32-61.compute-1.amazonaws.com:5432/d1vjo4h0fu1vkb?sslmode=require
    dataSourceClassName: org.postgresql.Driver
    username: inecnbgieajdyr
    password: 7673694fb8f5e9c0811ef4cdf997fd01f1df1865bcdc24a12283e0d3a9544fc8
    hikari:
      maximum-pool-size: 4
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true